### ISSUE TITLE
Update NR python scripts

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/Portal-Prototype-Working-Files#1]
Update the NR python scripts to follow the same habit of pulling data as dataframes and converting to JSON with python. This will allow us to create the JSON directly from the staging and production databases instead of using the dev database that Grant had used.

**Comment by cgettings** [comment]
- [x] EXP_indicator_json_writer.py
- [x] EXP_subtopic_json_writer.py
- [x] UHF_List.json
